apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello
  namespace: alexpython
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: localhost:5001/gitops-acg-dive:helloAlexv1.0
        imagePullPolicy: IfNotPresent