apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: alexpython
  labels:
    app: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: myapp
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000